#!/bin/bash
echo "🔨 Building Phase 6g..."

# ── 1. BACKEND: CV Download endpoint ──────────────────────────────────────────
python3 << 'PYEOF'
import os

path = os.path.expanduser('~/hireiq/backend/src/core-api/routes/candidates.ts')
with open(path, 'r') as f:
    content = f.read()

if 'cv-download' not in content:
    download_route = '''
// CV Download — generate PDF from stored cvStructured data
candidatesRouter.get('/:id/cv-download', async (req: AuthRequest, res: Response) => {
  try {
    const candidate = await prisma.candidate.findFirst({
      where: { id: req.params.id, agencyId: req.user!.agencyId }
    })
    if (!candidate) return res.status(404).json({ success: false, error: { code: 'NOT_FOUND', message: 'Candidate not found' } })

    const cv = (candidate.cvStructured as any) || {}
    const name = candidate.fullName || 'Unknown'
    const role = candidate.currentRole || cv.currentRole || 'Unknown Role'
    const years = candidate.yearsExperience || cv.yearsExperienceTotal || 0
    const email = candidate.email || cv.email || ''
    const skills: string[] = cv.skills || []
    const score = candidate.compositeScore

    // Build plain text CV
    const lines = [
      `${name}`,
      `${role}`,
      ``,
      `Contact: ${email} | Experience: ${years} years | Expected: AED ${candidate.salaryExpectation?.toLocaleString() || 'Not specified'}/month`,
      `Source: ${candidate.sourceChannel || 'unknown'} | Added: ${candidate.createdAt?.toISOString().slice(0,10) || ''}`,
      score ? `HireIQ Score: ${score}/100` : '',
      ``,
      `SKILLS`,
      `------`,
      skills.join(' · ') || 'Not specified',
      ``,
      `PROFESSIONAL SUMMARY`,
      `--------------------`,
      cv.summary || `${name} is an experienced ${role} with ${years} years of industry experience.`,
      ``,
    ]

    // Add experience if available
    if (cv.experience && Array.isArray(cv.experience)) {
      lines.push('WORK EXPERIENCE', '---------------')
      for (const exp of cv.experience.slice(0, 5)) {
        lines.push(`${exp.title || exp.role || ''} — ${exp.company || ''}`)
        lines.push(exp.description || exp.desc || '')
        lines.push('')
      }
    }

    // Add education
    if (cv.education) {
      lines.push('EDUCATION', '---------')
      lines.push(typeof cv.education === 'string' ? cv.education : JSON.stringify(cv.education))
      lines.push('')
    }

    // Add certifications
    if (cv.certifications && Array.isArray(cv.certifications)) {
      lines.push('CERTIFICATIONS', '--------------')
      for (const cert of cv.certifications) {
        lines.push(`• ${cert}`)
      }
    }

    lines.push('', `--- Generated by HireIQ · hireiq.ai ---`)

    const textContent = lines.filter(l => l !== null && l !== undefined).join('\\n')
    const filename = `${name.replace(/[^a-z0-9]/gi, '_')}_CV.txt`

    res.setHeader('Content-Type', 'text/plain; charset=utf-8')
    res.setHeader('Content-Disposition', `attachment; filename="${filename}"`)
    res.send(textContent)

  } catch (err: any) {
    res.status(500).json({ success: false, error: { code: 'DOWNLOAD_ERROR', message: err.message } })
  }
})
'''
    # Add before the last export or at the end
    content = content.rstrip() + '\n' + download_route
    with open(path, 'w') as f:
        f.write(content)
    print('  ✅ CV download endpoint added')
else:
    print('  ✅ CV download endpoint already exists')
PYEOF

# ── 2. FRONTEND: Download button in Talent Pool ────────────────────────────────
python3 << 'PYEOF'
import os, re

path = os.path.expanduser('~/hireiq/frontend/src/app/(dashboard)/talent-pool/page.tsx')
with open(path, 'r') as f:
    content = f.read()

# Add download function
if 'handleDownload' not in content:
    content = content.replace(
        "  return (",
        """  const handleDownload = async (candidateId: string, name: string) => {
    try {
      const token = (api as any).defaults?.headers?.common?.Authorization || ''
      const res = await fetch(`http://localhost:3001/api/v1/candidates/${candidateId}/cv-download`, {
        headers: token ? { Authorization: token } : {}
      })
      if (!res.ok) { throw new Error('Download failed') }
      const blob = await res.blob()
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `${name.replace(/[^a-z0-9]/gi, '_')}_CV.txt`
      a.click()
      URL.revokeObjectURL(url)
    } catch {
      toast.error('Download failed')
    }
  }

  return ("""
    )
    print('  ✅ handleDownload function added')

# Add download button to table row — after the status cell
if 'handleDownload' in content and 'Download CV' not in content:
    content = content.replace(
        "                  </td>\n                </tr>\n              ))}\n            </tbody>",
        """                  </td>
                  <td className="px-3 py-3">
                    <button
                      onClick={() => handleDownload(c.id, c.fullName || 'candidate')}
                      className="text-xs px-2.5 py-1.5 rounded-lg border font-medium transition-all hover:bg-gray-50"
                      style={{ borderColor: '#0A3D2E', color: '#0A3D2E' }}>
                      ↓ CV
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>"""
    )
    # Also add header
    content = content.replace(
        "['Name','Current Role','Experience','Score','Source','Added','Status'].map(h => (",
        "['Name','Current Role','Experience','Score','Source','Added','Status',''].map(h => ("
    )
    print('  ✅ Download button added to Talent Pool table')
else:
    print('  ✅ Already has download button or function missing')

with open(path, 'w') as f:
    f.write(content)
PYEOF

# ── 3. FRONTEND: Candidate profile drawer ──────────────────────────────────────
python3 << 'PYEOF'
import os

path = os.path.expanduser('~/hireiq/frontend/src/app/(dashboard)/talent-pool/page.tsx')
with open(path, 'r') as f:
    content = f.read()

if 'selectedCandidate' not in content:
    # Add state
    content = content.replace(
        "  const [filterScore, setFilterScore] = useState('')",
        "  const [filterScore, setFilterScore] = useState('')\n  const [selectedCandidate, setSelectedCandidate] = useState<any>(null)"
    )

    # Add profile drawer before closing div
    drawer = """
      {/* Candidate Profile Drawer */}
      {selectedCandidate && (
        <div className="fixed inset-0 z-50 flex justify-end" onClick={() => setSelectedCandidate(null)}>
          <div className="absolute inset-0 bg-black/30" />
          <div className="relative w-full max-w-md bg-white h-full shadow-2xl overflow-y-auto"
            onClick={e => e.stopPropagation()}>
            <div className="p-6">
              {/* Header */}
              <div className="flex items-start justify-between mb-5">
                <div className="flex items-center gap-3">
                  <div className="w-12 h-12 rounded-full flex items-center justify-center text-base font-bold flex-shrink-0"
                    style={{ background: '#E8F5EE', color: '#0A3D2E' }}>
                    {selectedCandidate.fullName?.split(' ').map((n: string) => n[0]).join('').slice(0,2)}
                  </div>
                  <div>
                    <h2 className="text-lg font-bold" style={{ color: '#0A3D2E' }}>{selectedCandidate.fullName}</h2>
                    <p className="text-sm text-gray-500">{selectedCandidate.currentRole}</p>
                  </div>
                </div>
                <button onClick={() => setSelectedCandidate(null)} className="text-gray-400 hover:text-gray-600 text-xl">×</button>
              </div>

              {/* Score badge */}
              {selectedCandidate.compositeScore && (
                <div className="mb-4 p-3 rounded-xl flex items-center gap-3"
                  style={{ background: selectedCandidate.compositeScore >= 75 ? '#DCFCE7' : selectedCandidate.compositeScore >= 55 ? '#FEF3C7' : '#FEE2E2' }}>
                  <span className="text-2xl font-bold"
                    style={{ color: selectedCandidate.compositeScore >= 75 ? '#166534' : selectedCandidate.compositeScore >= 55 ? '#92400E' : '#991B1B' }}>
                    {selectedCandidate.compositeScore}
                  </span>
                  <div>
                    <p className="text-xs font-semibold" style={{ color: '#374151' }}>HireIQ Score</p>
                    <p className="text-xs text-gray-500">
                      {selectedCandidate.compositeScore >= 75 ? 'Strong match' : selectedCandidate.compositeScore >= 55 ? 'Good match' : 'Partial match'}
                    </p>
                  </div>
                </div>
              )}

              {/* Details */}
              <div className="space-y-4">
                <div>
                  <p className="text-xs font-medium text-gray-400 uppercase mb-1">Contact</p>
                  <p className="text-sm text-gray-700">{selectedCandidate.email || '—'}</p>
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <p className="text-xs font-medium text-gray-400 uppercase mb-1">Experience</p>
                    <p className="text-sm font-medium text-gray-700">{selectedCandidate.yearsExperience ? `${selectedCandidate.yearsExperience} years` : '—'}</p>
                  </div>
                  <div>
                    <p className="text-xs font-medium text-gray-400 uppercase mb-1">Salary Expected</p>
                    <p className="text-sm font-medium text-gray-700">
                      {selectedCandidate.salaryExpectation ? `AED ${selectedCandidate.salaryExpectation.toLocaleString()}` : '—'}
                    </p>
                  </div>
                </div>
                <div>
                  <p className="text-xs font-medium text-gray-400 uppercase mb-1">Source</p>
                  <span className="text-xs px-2 py-0.5 rounded-full text-white capitalize"
                    style={{ background: '#0A3D2E' }}>
                    {(selectedCandidate.sourceChannel || 'other').replace(/_/g,' ')}
                  </span>
                </div>

                {/* Skills */}
                {(selectedCandidate.cvStructured as any)?.skills?.length > 0 && (
                  <div>
                    <p className="text-xs font-medium text-gray-400 uppercase mb-2">Skills</p>
                    <div className="flex flex-wrap gap-1.5">
                      {((selectedCandidate.cvStructured as any)?.skills || []).map((s: string, i: number) => (
                        <span key={i} className="text-xs px-2 py-0.5 rounded-full"
                          style={{ background: '#E8F5EE', color: '#0A3D2E' }}>
                          {s}
                        </span>
                      ))}
                    </div>
                  </div>
                )}

                {/* Job History */}
                <div>
                  <p className="text-xs font-medium text-gray-400 uppercase mb-2">Applied Jobs</p>
                  <div className="space-y-2">
                    <div className="p-3 rounded-xl border border-gray-100">
                      <div className="flex items-center justify-between">
                        <p className="text-sm font-medium text-gray-800">
                          {(selectedCandidate.dataTags as any)?.jobTitle || selectedCandidate.currentRole || 'Current role'}
                        </p>
                        {selectedCandidate.compositeScore && (
                          <span className="text-xs font-bold px-2 py-0.5 rounded-full"
                            style={{ background: '#E8F5EE', color: '#0A3D2E' }}>
                            {selectedCandidate.compositeScore}
                          </span>
                        )}
                      </div>
                      <p className="text-xs text-gray-400 mt-0.5 capitalize">
                        {selectedCandidate.pipelineStage?.replace(/_/g,' ')} · {selectedCandidate.createdAt ? new Date(selectedCandidate.createdAt).toLocaleDateString('en-GB', { day:'numeric', month:'short', year:'numeric' }) : ''}
                      </p>
                    </div>
                  </div>
                </div>
              </div>

              {/* Actions */}
              <div className="mt-6 flex gap-3">
                <button
                  onClick={() => handleDownload(selectedCandidate.id, selectedCandidate.fullName || 'candidate')}
                  className="flex-1 py-2.5 text-sm font-semibold rounded-xl border-2 transition-all"
                  style={{ borderColor: '#0A3D2E', color: '#0A3D2E' }}>
                  ↓ Download CV
                </button>
              </div>
            </div>
          </div>
        </div>
      )}"""

    content = content.replace(
        "    </div>\n  )\n}",
        drawer + "\n    </div>\n  )\n}"
    )

    # Make name clickable to open drawer
    content = content.replace(
        "                      <span className=\"text-sm font-medium text-gray-800\">{c.fullName || 'Unknown'}</span>",
        "                      <button onClick={() => setSelectedCandidate(c)} className=\"text-sm font-medium text-gray-800 hover:underline text-left\" style={{ color: '#0A3D2E' }}>{c.fullName || 'Unknown'}</button>"
    )

    with open(path, 'w') as f:
        f.write(content)
    print('  ✅ Profile drawer added — click name to open')
else:
    print('  ✅ Profile drawer already exists')
PYEOF

# ── 4. CLEAR CACHE ──────────────────────────────────────────────────────────────
rm -rf ~/hireiq/frontend/.next 2>/dev/null
echo "  ✅ Cache cleared"
echo ""
echo "✅ Phase 6g complete"
echo "Next: restart Core API and frontend"
