'use client'
// src/components/dashboard/LockedFeaturesGrid.tsx
import { LockClosedIcon } from '@heroicons/react/24/solid'

const features = [
  { icon: '📞', title: 'AI Reference Check Agent', desc: "Automated WhatsApp reference conversations with your candidates' referees. 8-question behavior-event format.", eta: 'Coming Q3 2026' },
  { icon: '🎥', title: 'AI Video Interview Agent', desc: 'Conduct structured AI video interviews. Transcript, scoring, and highlight reels auto-generated.', eta: 'Coming Q3 2026' },
  { icon: '🇸🇦', title: 'Saudization Dashboard', desc: 'Real-time Nitaqat compliance tracking, quota forecasting, and HRSD report generation.', eta: 'Coming Q4 2026' },
  { icon: '📊', title: 'Skills Assessment Engine', desc: 'Role-specific technical assessments generated by AI and delivered via WhatsApp.', eta: 'Coming Q4 2026' },
  { icon: '🎯', title: 'AI Job Description Writer', desc: 'Professional bilingual JDs with Gulf salary benchmarks in 3 minutes.', eta: 'Coming Q3 2026' },
  { icon: '🔄', title: 'Job Board Integration', desc: 'Post directly to Bayt, LinkedIn, and Gulf Talent with one click.', eta: 'Coming Q3 2026' },
]

export function LockedFeaturesGrid() {
  return (
    <div>
      <div className="flex items-center gap-3 mb-4">
        <div className="flex-1 h-px bg-gray-200" />
        <span className="text-xs font-semibold text-gray-400 uppercase tracking-wider px-2">Platform Roadmap</span>
        <div className="flex-1 h-px bg-gray-200" />
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-3">
        {features.map((f) => (
          <div
            key={f.title}
            className="bg-white border border-gray-100 rounded-xl p-4 opacity-70 relative overflow-hidden group hover:opacity-90 transition-opacity cursor-default"
          >
            {/* Lock overlay */}
            <div className="absolute top-3 right-3">
              <LockClosedIcon className="w-3.5 h-3.5 text-gray-300" />
            </div>
            <div className="flex items-start gap-3">
              <div className="w-9 h-9 bg-gray-100 rounded-lg flex items-center justify-center flex-shrink-0 text-lg grayscale">
                {f.icon}
              </div>
              <div className="flex-1 min-w-0">
                <p className="text-sm font-semibold text-gray-600">{f.title}</p>
                <p className="text-xs text-gray-400 mt-0.5 leading-relaxed">{f.desc}</p>
                <span className="inline-block mt-2 text-xs font-medium text-brand-gold bg-brand-gold/10 px-2 py-0.5 rounded-full">
                  {f.eta}
                </span>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}
